server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - "content-type"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: measurement-service
          uri: lb://MEASUREMENT-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
